apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: db
spec:
  containers:
  - name: container-mysql
    image: mysql
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_DATABASE
        value: "loja"
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "1"