apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mysql
spec:
  selector:
    matchLabels:
      app: mysql-app-name
  serviceName: mysql-servicename
  template:
    metadata:
      labels:
        name: mysql-labels-name
    spec:
      containers:
      - name: container-mysql
        image: mysql:5.7.19
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "loja"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        volumeMounts:
        - name: volume-mysql
          mountPath: /var/lib/mysql
    volumes:
    - name: volume-mysql
      persistentVolumeClaim: 
        claimName: configuracao-mysql